# Generated by Django 3.2.6 on 2021-12-05 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211206_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='post.postcategory'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
