# Generated by Django 3.2.6 on 2021-12-05 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.postcategory'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
