# Generated by Django 3.2.6 on 2021-12-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, default='Anonymous user', max_length=100),
        ),
    ]
